### ISSUE TITLE
Maven repo not found

### ISSUE THREAD

**Issue by nothinn** [ucb-bar/chisel-testers2#129]
I have an issue where I have tried adding the tester as described in the readme. However, when running the test, it claims that the maven repo is not found and when I look in the maven repo, it is not there either:

```shell
[error] (lib / update) sbt.librarymanagement.ResolveException: Error downloading edu.berkeley.cs:chiseltest_2.12:0.1-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/simon/.ivy2/local/edu.berkeley.cs/chiseltest_2.12/0.1-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/chiseltest_2.12/0.1-SNAPSHOT/chiseltest_2.12-0.1-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/edu/berkeley/cs/chiseltest_2.12/0.1-SNAPSHOT/chiseltest_2.12-0.1-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/edu/berkeley/cs/chiseltest_2.12/0.1-SNAPSHOT/chiseltest_2.12-0.1-SNAPSHOT.pom
[error] Total time: 5 s, completed Feb 21, 2020 3:14:09 PM
```

This is with the following in my build.sbt:
```sbt
 libraryDependencies ++= Seq("edu.berkeley.cs" %% "chiseltest" % "0.1-SNAPSHOT")
```

When changing the imports to *chisel3.tester.* instead of *chiseltest.*  and using
``` sbt
libraryDependencies ++= Seq("edu.berkeley.cs" %% "chisel-testers2" % "0.1-SNAPSHOT")
```
in the build.sbt file, then it works fine. I am using *chisel3 3.3-SNAPSHOT* with it.

**Comment by edwardcwang** [comment]
Hello Simon, thank you for your interest in Chisel and ChiselTest! Could you please try with the following line in `build.sbt` and let us know if it works?

```
libraryDependencies ++= Seq("edu.berkeley.cs" %% "chiseltest" % "0.2-SNAPSHOT")
```

**Comment by nothinn** [comment]
That worked perfectly. Now I can do concurrent testing on my SoC!

Thank you. (Remember to update the Readme for other users)

**Comment by schoeberl** [comment]
If you want to avoid the need of an Internet connection every time you build your project, you could use the libraries with a version and avoiding SNAPSHOT. For the tester the latest version is:

libraryDependencies += "edu.berkeley.cs" %% "chisel-testers2" % "0.1.2"

Looks like we are waiting for publishing of a 0.2.x as chiseltest on Maven.

Martin
