### ISSUE TITLE
Verilated::flushCall renamed in newer versions of verilator

### ISSUE THREAD

**Issue by jiegec** [ucb-bar/chisel-testers2#177]
Code change in verilator: https://github.com/verilator/verilator/commit/fac89c5d6233f900d0e382bde21526400427e388#diff-6c80b812607617c162e46fd56e6579c8

Related code in chisel-testers2:
https://github.com/ucb-bar/chisel-testers2/blob/db85e6fcb5ce2d8397ea0d9ed1745cdd5b7b9e35/src/main/scala/chiseltest/legacy/backends/verilator/VerilatorCppHarnessGenerator.scala#L148

**Comment by ljwljwljwljw** [comment]
I have same problem, maybe "Verilated::flushCall()" need to be changed to "Verilated::runFlushCallbacks()"?

**Comment by ducky64** [comment]
I think it makes sense for us to keep our Verilator version in sync with the [version recommended by chisel3's setup](https://github.com/freechipsproject/chisel3/blob/master/SETUP.md), which is currently 4.016.

Though, feel free to make a PR if you have code that updates behavior for newer versions while remaining 4.016 compatibility?

**Comment by ljwljwljwljw** [comment]
> I think it makes sense for us to keep our Verilator version in sync with the [version recommended by chisel3's setup](https://github.com/freechipsproject/chisel3/blob/master/SETUP.md), which is currently 4.016.
> 
> Though, feel free to make a PR if you have code that updates behavior for newer versions while remaining 4.016 compatibility?

Thanks for you advice, here(#187) is my PR, I just simply use `verilator --version` to check verilator's version as a temporary solution, I noticed that in #156 we can use our own cpp harness or `SimulatorBinary`, after that PR this problem will be well solved.
