### ISSUE TITLE
Invoke Verilator in-process to speed it up and make it more robust

### ISSUE THREAD

**Issue by oharboe** [ucb-bar/chisel-testers2#181]
Rather than communicating across processes, build a DLL/.so file and use JNI (or perhaps there's some more modern variant thereof in JVM, I'm a bit out of touch...) to drive the simulation.

The advantage is:

- speed
- occasionally, I'll ctrl-c some application and I have a 100% busy Verilator process running for a few hours. I notice this because the fan on my laptop doesn't turn off.
- once in a blue moon, the communication channel fails on our build server.

**Comment by ekiwi** [comment]
this should now be fixed
