### ISSUE TITLE
How to cite tester2

### ISSUE THREAD

**Issue by schoeberl** [ucb-bar/chisel-testers2#189]
I am about to submit a paper where I am using tester2/ChiselTest in the evaluation and would like to correctly cite this work.

Cheers,
Martin

**Comment by ducky64** [comment]
Uh, since there's no publication on this (yet?), just drop the GitHub link?

And at some point we'll probably get around to changing all the naming to ChiselTest, but I think GitHub is pretty good about repository redirects?

**Comment by schoeberl** [comment]
What about having a technical report published by UCB? A GitHub link is a very weak reference.

Yes, getting the renaming done would be good. And than call it version 1.0 and be it the official Chisel testing framework ;-)

Cheers,
Martin

**Comment by ducky64** [comment]
A technical report might be a possibility, but probably not a near-term one.

I'm actually not sure what is holding up the repo rename. It looks like we've already renamed the package in build.sbt (though I think the publish scripts continue to also publish under chisel-testers2 for compatibility?).

**Comment by schoeberl** [comment]
I am using the following and will close this.
```
@ELECTRONIC{chisel:tester2,
  author = {Richard Lin},
  title = {{ChiselTest}},
  howpublished = {https://github.com/ucb-bar/chisel-testers2}
}
```
