### ISSUE TITLE
How to perform tests more than 1000 cycles?

### ISSUE THREAD

**Issue by HaFred** [ucb-bar/chisel-testers2#193]
I have a chisel-tester2 testbench that could work on the DUT. Now I poke in more data to the chisel [SRAM](https://www.chisel-lang.org/chisel3/memories.html#syncreadmem-sequentialsynchronous-read-sequentialsynchronous-write) for a more complicated testcase. 
It failed with the error `timeout on Clock(IO clock in Conv2ProcessingElement) at 1000 idle cycles`. Is it possible to continue the test more than 1000 clock cycles?

**Comment by nrother** [comment]
You can can use `dut.clock.setTimeout()` to change the timeout of 1000 cycles. Setting it to zero should disable the timeout altogether.
