### ISSUE TITLE
Use JNI to speed up performance of interfacing with simulators

### ISSUE THREAD

**Issue by edwardcwang** [ucb-bar/chisel-testers2#28]
See https://github.com/freechipsproject/chisel3/pull/798

**Comment by grebe** [comment]
See also [my chisel-testers WiP PR](https://github.com/freechipsproject/chisel-testers/pull/233)

**Comment by ekiwi** [comment]
We are using JNA now with Verilator. With JNI the problem is that it is tricky to load more than one simulation at a time into the JVM. There could be a way to further speed things up by essentially implementing our own JNA-lite. If anyone is interested in taking that on, please talk to me.
