### ISSUE TITLE
Verilator executable not killed after test is interrupted or fails

### ISSUE THREAD

**Issue by kammoh** [ucb-bar/chisel-testers2#284]
After a test is interrupted (e.g. ctrl+C or from an IDE e.g. vscode/metals) and in some situations after a test-fail exception, the Verilator generated executable model keeps running forever, using 100% of core CPU.
This is pretty annoying, especially during development/debug cycles.

Running on macOS ATM, so not sure if the behaviour is the same on other platforms as well.

**Comment by ekiwi** [comment]
This should now be fixed since we load the verilator simulation as a library and do not run it as a separate process anymore. Now there is room for other kinds of resource leakages though :)
