### ISSUE TITLE
New unit-test added: Unsatisfied link error with Verilator when using asserts in tests

### ISSUE THREAD

**Issue by oharboe** [ucb-bar/chisel-testers2#366]
This was with 0.5-SNAPSHOT as of writing.

I got this error when I tried 0.5-SNAPSHOT today.

Ubuntu 20.04

```
[info]   java.lang.UnsatisfiedLinkError: Unable to load library '.../verilated/VDoohickeyTestBench_123':
[info] .../verilated/VDoohickeyTestBench_123': undefined symbol: _Z13sc_time_stampv
```

**Comment by oharboe** [comment]
Reproducible with pull request #367

**Comment by ekiwi** [comment]
Thanks for all the reports @oharboe !

**Comment by ekiwi** [comment]
Patch just got in and will be published in ~10-15min. Keep these reports coming and I will try to fix them. Thanks you so much!
