### ISSUE TITLE
Bug: Poked Value resetted on end of Test

### ISSUE THREAD

**Issue by Tarirah** [ucb-bar/chisel-testers2#396]
Apparently, the value of a poked input are resetted on the end of the test, which for example makes asserts fail.
According to this stackoverflow question: https://stackoverflow.com/questions/69093953/why-do-poked-values-change-on-last-clock-cycle-in-chiseltest-thus-failing-asser/69106387#69106387 this has to do with scoping of the test.

I've attached the minimum example that demonstrates the issue:
```scala
package stack_overflow_demo

import chisel3._
import chisel3.tester._
import org.scalatest.FreeSpec
import chisel3.experimental.BundleLiterals._

class AssertFail extends Module {
    val io = IO(new Bundle {
        val input = Input(UInt(2.W))
    })

    printf("%d\n", io.input) // prints 3 and then 0

    assert(io.input === 3.U) // fails, apparently on the second cycle
}

class AssertTest extends FreeSpec with ChiselScalatestTester {
    "break" in {
        test(new AssertFail) { dut =>
            dut.io.input.poke(3.U)
            dut.clock.step()
        }
    }
}

```

**Comment by ekiwi** [comment]
Thanks! We investigated this problem and it is 100% a bug in `chiseltest`. We are going to try and get rid of the final clock step that `chiseltest` always adds without the user explicitly calling `step`.
