### ISSUE TITLE
Legacy verilator backend does not printf

### ISSUE THREAD

**Issue by kammoh** [ucb-bar/chisel-testers2#50]
`printf` does not show any output in the recently committed (legacy/experimental) verilator back-end.

**Comment by chick** [comment]
I believe the following PR will fix this. Fixes printf's not showing up. PR #51

**Comment by chick** [comment]
@kammoh This should be fixed now. Please close when fix is verified.

**Comment by kammoh** [comment]
Fixed! Thanks for the quick patch!
