### ISSUE TITLE
implicit conver to DecoupledIO does not work

### ISSUE THREAD

**Issue by ShuyunJia** [ucb-bar/chisel-testers2#89]
The `TestAdapters`  suggest to use implicit conversion to `DecoupledDriver` 
https://github.com/ucb-bar/chisel-testers2/blob/ea5e81f2e54f2df4d5cd34d8e7ece2a69fab0f86/src/main/scala/chisel3/tester/TestAdapters.scala#L9

It woks fine for `DecoupledIO`. However, it does not work for `IrrevocableIO`. I have to force the type conversion to `DecoupledIO`: 
```
it should "run implicit convert" in {
    test(new Module{
      val io = IO( new Bundle{
        val in = Flipped(Irrevocable(UInt(8.W)))
        val out = Irrevocable(UInt(8.W))
      })
    }).withAnnotations(Seq(WriteVcdAnnotation)) { c =>
      Decoupled(c.io.in).initSource.setSourceClock(c.clock)
    }
  }
```

**Comment by ducky64** [comment]
Resolved by #90, I think?
